window.Modernizr=function(window,a,b){function c(a){s.cssText=a}function d(a,b){return c(w.join(a+";")+(b||""))}function e(a,b){return typeof a===b}function f(a,b){return!!~(""+a).indexOf(b)
}function g(a,c){for(var d in a){var e=a[d];if(!f(e,"-")&&s[e]!==b)return"pfx"==c?e:!0}return!1}function h(a,c,d){for(var f in a){var g=c[a[f]];if(g!==b)return d===!1?a[f]:e(g,"function")?g.bind(d||c):g
}return!1}function i(a,b,c){var d=a.charAt(0).toUpperCase()+a.slice(1),f=(a+" "+y.join(d+" ")+d).split(" ");return e(b,"string")||e(b,"undefined")?g(f,b):(f=(a+" "+z.join(d+" ")+d).split(" "),h(f,b,c))
}function j(){n.input=function(b){for(var c=0,d=b.length;d>c;c++)D[b[c]]=!!(b[c]in t);return D.list&&(D.list=!(!a.createElement("datalist")||!window.HTMLDataListElement)),D
}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" ")),n.inputtypes=function(c){for(var d,e,f,g=0,h=c.length;h>g;g++)t.setAttribute("type",e=c[g]),d="text"!==t.type,d&&(t.value=u,t.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(e)&&t.style.WebkitAppearance!==b?(p.appendChild(t),f=a.defaultView,d=f.getComputedStyle&&"textfield"!==f.getComputedStyle(t,null).WebkitAppearance&&0!==t.offsetHeight,p.removeChild(t)):/^(search|tel)$/.test(e)||(d=/^(url|email)$/.test(e)?t.checkValidity&&t.checkValidity()===!1:t.value!=u)),C[c[g]]=!!d;
return C}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var k,l,m="2.8.2",n={},o=!0,p=a.documentElement,q="modernizr",r=a.createElement(q),s=r.style,t=a.createElement("input"),u=":)",v={}.toString,w=" -webkit- -moz- -o- -ms- ".split(" "),x="Webkit Moz O ms",y=x.split(" "),z=x.toLowerCase().split(" "),A={svg:"http://www.w3.org/2000/svg"},B={},C={},D={},E=[],F=E.slice,G=function(b,c,d,e){var f,g,h,i,j=a.createElement("div"),k=a.body,l=k||a.createElement("body");
if(parseInt(d,10))for(;d--;)h=a.createElement("div"),h.id=e?e[d]:q+(d+1),j.appendChild(h);return f=["&#173;",'<style id="s',q,'">',b,"</style>"].join(""),j.id=q,(k?j:l).innerHTML+=f,l.appendChild(j),k||(l.style.background="",l.style.overflow="hidden",i=p.style.overflow,p.style.overflow="hidden",p.appendChild(l)),g=c(j,b),k?j.parentNode.removeChild(j):(l.parentNode.removeChild(l),p.style.overflow=i),!!g
},H=function(a){var b=window.matchMedia||window.msMatchMedia;if(b)return b(a)&&b(a).matches||!1;var c;return G("@media "+a+" { #"+q+" { position: absolute; } }",function(a){c="absolute"==(window.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position
}),c},I=function(){function c(c,f){f=f||a.createElement(d[c]||"div"),c="on"+c;var g=c in f;return g||(f.setAttribute||(f=a.createElement("div")),f.setAttribute&&f.removeAttribute&&(f.setAttribute(c,""),g=e(f[c],"function"),e(f[c],"undefined")||(f[c]=b),f.removeAttribute(c))),f=null,g
}var d={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return c}(),J={}.hasOwnProperty;l=e(J,"undefined")||e(J.call,"undefined")?function(a,b){return b in a&&e(a.constructor.prototype[b],"undefined")
}:function(a,b){return J.call(a,b)},Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;
var c=F.call(arguments,1),d=function(){if(this instanceof d){var e=function(){};e.prototype=b.prototype;var f=new e,g=b.apply(f,c.concat(F.call(arguments)));
return Object(g)===g?g:f}return b.apply(a,c.concat(F.call(arguments)))};return d}),B.flexbox=function(){return i("flexWrap")},B.flexboxlegacy=function(){return i("boxDirection")
},B.canvas=function(){var b=a.createElement("canvas");return!(!b.getContext||!b.getContext("2d"))},B.canvastext=function(){return!(!n.canvas||!e(a.createElement("canvas").getContext("2d").fillText,"function"))
},B.webgl=function(){return!!window.WebGLRenderingContext},B.touch=function(){var b;return"ontouchstart"in window||window.DocumentTouch&&a instanceof DocumentTouch?b=!0:G(["@media (",w.join("touch-enabled),("),q,")","{#modernizr{top:9px;position:absolute}}"].join(""),function(a){b=9===a.offsetTop
}),b},B.geolocation=function(){return"geolocation"in navigator},B.postmessage=function(){return!!window.postMessage},B.websqldatabase=function(){return!!window.openDatabase
},B.indexedDB=function(){return!!i("indexedDB",window)},B.hashchange=function(){return I("hashchange",window)&&(a.documentMode===b||a.documentMode>7)},B.history=function(){return!(!window.history||!history.pushState)
},B.draganddrop=function(){var b=a.createElement("div");return"draggable"in b||"ondragstart"in b&&"ondrop"in b},B.websockets=function(){return"WebSocket"in window||"MozWebSocket"in window
},B.rgba=function(){return c("background-color:rgba(150,255,150,.5)"),f(s.backgroundColor,"rgba")},B.hsla=function(){return c("background-color:hsla(120,40%,100%,.5)"),f(s.backgroundColor,"rgba")||f(s.backgroundColor,"hsla")
},B.multiplebgs=function(){return c("background:url(https://),url(https://),red url(https://)"),/(url\s*\(.*?){3}/.test(s.background)},B.backgroundsize=function(){return i("backgroundSize")
},B.borderimage=function(){return i("borderImage")},B.borderradius=function(){return i("borderRadius")},B.boxshadow=function(){return i("boxShadow")},B.textshadow=function(){return""===a.createElement("div").style.textShadow
},B.opacity=function(){return d("opacity:.55"),/^0.55$/.test(s.opacity)},B.cssanimations=function(){return i("animationName")},B.csscolumns=function(){return i("columnCount")
},B.cssgradients=function(){var a="background-image:",b="gradient(linear,left top,right bottom,from(#9f9),to(white));",d="linear-gradient(left top,#9f9, white);";
return c((a+"-webkit- ".split(" ").join(b+a)+w.join(d+a)).slice(0,-a.length)),f(s.backgroundImage,"gradient")},B.cssreflections=function(){return i("boxReflect")
},B.csstransforms=function(){return!!i("transform")},B.csstransforms3d=function(){var a=!!i("perspective");return a&&"webkitPerspective"in p.style&&G("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b){a=9===b.offsetLeft&&3===b.offsetHeight
}),a},B.csstransitions=function(){return i("transition")},B.fontface=function(){var b;return G('@font-face {font-family:"font";src:url("https://")}',function(c,d){var e=a.getElementById("smodernizr"),f=e.sheet||e.styleSheet,g=f?f.cssRules&&f.cssRules[0]?f.cssRules[0].cssText:f.cssText||"":"";
b=/src/i.test(g)&&0===g.indexOf(d.split(" ")[0])}),b},B.generatedcontent=function(){var a;return G(["#",q,"{font:0/0 a}#",q,':after{content:"',u,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=b.offsetHeight>=3
}),a},B.video=function(){var b=a.createElement("video"),c=!1;try{(c=!!b.canPlayType)&&(c=new Boolean(c),c.ogg=b.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),c.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),c.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,""))
}catch(d){}return c},B.audio=function(){var b=a.createElement("audio"),c=!1;try{(c=!!b.canPlayType)&&(c=new Boolean(c),c.ogg=b.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),c.mp3=b.canPlayType("audio/mpeg;").replace(/^no$/,""),c.wav=b.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),c.m4a=(b.canPlayType("audio/x-m4a;")||b.canPlayType("audio/aac;")).replace(/^no$/,""))
}catch(d){}return c},B.localstorage=function(){try{return localStorage.setItem(q,q),localStorage.removeItem(q),!0}catch(a){return!1}},B.sessionstorage=function(){try{return sessionStorage.setItem(q,q),sessionStorage.removeItem(q),!0
}catch(a){return!1}},B.webworkers=function(){return!!window.Worker},B.applicationcache=function(){return!!window.applicationCache},B.svg=function(){return!!a.createElementNS&&!!a.createElementNS(A.svg,"svg").createSVGRect
},B.inlinesvg=function(){var b=a.createElement("div");return b.innerHTML="<svg/>",(b.firstChild&&b.firstChild.namespaceURI)==A.svg},B.smil=function(){return!!a.createElementNS&&/SVGAnimate/.test(v.call(a.createElementNS(A.svg,"animate")))
},B.svgclippaths=function(){return!!a.createElementNS&&/SVGClipPath/.test(v.call(a.createElementNS(A.svg,"clipPath")))};for(var K in B)l(B,K)&&(k=K.toLowerCase(),n[k]=B[K](),E.push((n[k]?"":"no-")+k));
return n.input||j(),n.addTest=function(a,c){if("object"==typeof a)for(var d in a)l(a,d)&&n.addTest(d,a[d]);else{if(a=a.toLowerCase(),n[a]!==b)return n;
c="function"==typeof c?c():c,"undefined"!=typeof o&&o&&(p.className+=" "+(c?"":"no-")+a),n[a]=c}return n},c(""),r=t=null,function(window,a){function b(a,b){var c=a.createElement("p"),d=a.getElementsByTagName("head")[0]||a.documentElement;
return c.innerHTML="x<style>"+b+"</style>",d.insertBefore(c.lastChild,d.firstChild)}function c(){var a=r.elements;return"string"==typeof a?a.split(" "):a
}function d(a){var b=q[a[o]];return b||(b={},p++,a[o]=p,q[p]=b),b}function e(b,c,e){if(c||(c=a),j)return c.createElement(b);e||(e=d(c));var f;return f=e.cache[b]?e.cache[b].cloneNode():n.test(b)?(e.cache[b]=e.createElem(b)).cloneNode():e.createElem(b),!f.canHaveChildren||m.test(b)||f.tagUrn?f:e.frag.appendChild(f)
}function f(b,e){if(b||(b=a),j)return b.createDocumentFragment();e=e||d(b);for(var f=e.frag.cloneNode(),g=0,h=c(),i=h.length;i>g;g++)f.createElement(h[g]);
return f}function g(a,b){b.cache||(b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag()),a.createElement=function(c){return r.shivMethods?e(c,a,b):b.createElem(c)
},a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/[\w\-]+/g,function(a){return b.createElem(a),b.frag.createElement(a),'c("'+a+'")'
})+");return n}")(r,b.frag)}function h(c){c||(c=a);var e=d(c);return!r.shivCSS||i||e.hasCSS||(e.hasCSS=!!b(c,"article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}")),j||g(c,e),c
}var i,j,k="3.7.0",l=window.html5||{},m=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,n=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,o="_html5shiv",p=0,q={};
!function(){try{var b=a.createElement("a");b.innerHTML="<xyz></xyz>",i="hidden"in b,j=1==b.childNodes.length||function(){a.createElement("a");var b=a.createDocumentFragment();
return"undefined"==typeof b.cloneNode||"undefined"==typeof b.createDocumentFragment||"undefined"==typeof b.createElement}()}catch(c){i=!0,j=!0}}();var r={elements:l.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:k,shivCSS:l.shivCSS!==!1,supportsUnknownElements:j,shivMethods:l.shivMethods!==!1,type:"default",shivDocument:h,createElement:e,createDocumentFragment:f};
window.html5=r,h(a)}(this,a),n._version=m,n._prefixes=w,n._domPrefixes=z,n._cssomPrefixes=y,n.mq=H,n.hasEvent=I,n.testProp=function(a){return g([a])},n.testAllProps=i,n.testStyles=G,n.prefixed=function(a,b,c){return b?i(a,b,c):i(a,"pfx")
},p.className=p.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(o?" js "+E.join(" "):""),n}(this,this.document);